export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_TIME_REG = "ADD_TIME_REG";
export const UPDATE_PROJECT_COMPLETED = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_TIME_REG = "DELETE_TIME_REG";
export const UPDATE_PROJECT_TITLE = "UPDATE_PROJECT_TITLE";
export const UPDATE_PROJECT_DEADLINE = "UPDATE_PROJECT_DEADLINE";
